version: "3"

services:
  attacker:
    image: 'handsonsecurity/seed-ubuntu:large'
    container_name: seed-attacker
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - './volumes:/volumes'
    network_mode: host
  
  HostA:
    image: 'handsonsecurity/seed-ubuntu:large'
    container_name: host-192.168.60.5
    tty: true
    cap_add:
      - ALL
    networks:
      net-192.168.60.0:
        ipv4_address: 192.168.60.5
  
  HostB:
    image: 'handsonsecurity/seed-ubuntu:large'
    container_name: host-192.168.60.6
    tty: true
    cap_add:
      - ALL
    networks:
      net-192.168.60.0:
        ipv4_address: 192.168.60.6
  
  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    tty: true
    stdin_open: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - './volumes:/volumes'
    networks:
      net-192.168.60.0:
        ipv4_address: 192.168.60.101
    command:
      - /bin/bash
  
  metasploitable:
    image: tleemcjr/metasploitable2
    container_name: metasploitable
    restart: always
    networks:
      net-192.168.60.0:
        ipv4_address: 192.168.60.102
    command: sh -c "/bin/services.sh && bash"
  
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    restart: always
    ports:
      - '8081:80'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      net-192.168.60.0:
        ipv4_address: 192.168.60.103
  
  juice-shop:
    image: bkimminich/juice-shop
    container_name: juice-shop
    restart: always
    ports:
      - '3000:3000'
    networks:
      net-192.168.60.0:
        ipv4_address: 192.168.60.104

  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
    restart: always
    networks:
      net-192.168.60.0:
        ipv4_address: 192.168.60.105

networks:
  net-192.168.60.0:
    name: net-192.168.60.0
    ipam:
      config:
        - subnet: 192.168.60.0/24
